server:
  port: 8951

eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster01:8761/eureka/,http://eureka-cluster02:8762/eureka/
spring:
  application:
    name: eureka-rabbitmq-producer
  profiles: mq01
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: cloudtest

---
server:
  port: 8952

eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster01:8761/eureka/,http://eureka-cluster02:8762/eureka/
spring:
  application:
    name: eureka-rabbitmq-consumer
  profiles: mq02
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: cloudtest



